name: load-test

on: [push]

jobs:
  load-test:
    name: load-test-spark
    runs-on: ubuntu-latest
    env:
      SPARK_MASTER: local[*]
      ZINGG_HOME: /home/administrator/zingg/zinggOSS/assembly/target
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7 #install the python needed
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: temurin
      - name: setup spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.5.3'
          hadoop-version: '3'
      - name: check spark
        run: spark-submit --version
      - name: mvn clean
        run: mvn clean
      - name: Build with Maven
        run: mvn clean compile package -DskipTests=true
      - name: execute py script
        run: |
          python loadTest.py
          git config user.name nitish
          git config user.email nitish1814@github.com
          git add .
          git commit -m "report generated"
          git push
